//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyConfiguration("Retail")]
[assembly: AssemblyCompany("Tim Jones")]
[assembly: AssemblyProduct("Meshellator")]
[assembly: AssemblyCopyright("Copyright ©2011 Tim Jones")]
[assembly: AssemblyTrademark("roastedamoeba.com")]
[assembly: ComVisible(false)]

[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyVersion("1.0.0.0")]